# Generated by Django 2.0.2 on 2018-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('employeename', models.CharField(blank=True, max_length=120, null=True)),
                ('contact', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.CharField(choices=[('Sales & marketing', 'Sales & marketing'), ('Webapp Associate', 'Webapp Associate'), ('Webapp Architect', 'Webapp Architect'), ('Webapp Engineer', 'Webapp Engineer'), ('CMS & Ecomm', 'CMS & Ecomm'), ('System Admin', 'System Admin'), ('UI/UX', 'UI/UX'), ('Quality Analyst', 'Quality Analyst'), ('HR', 'HR')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
