# Generated by Django 2.0.2 on 2018-06-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_auto_20180611_1214'),
        ('Employee_Registration', '0002_auto_20180611_1214'),
        ('Book_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DateField()),
                ('renew', models.DateField()),
                ('BookId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_BookId_profile', to='library_management.Book')),
                ('Employeeid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_Employeeid_profile', to='Employee_Registration.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Bookdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeeid', models.CharField(blank=True, max_length=120, null=True)),
                ('assignbook', models.ManyToManyField(related_name='custom_Employeeid_profile', to='library_management.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
