# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 22:13
from __future__ import unicode_literals

from django.apps import AppConfig


class PostingsConfig(AppConfig):
    name = 'Employee_Registration'
