# Generated by Django 2.0.2 on 2018-06-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(blank=True, max_length=120, null=True)),
                ('Author', models.CharField(blank=True, max_length=120, null=True)),
                ('Publication', models.CharField(blank=True, max_length=120, null=True)),
                ('Published', models.CharField(blank=True, max_length=120, null=True)),
                ('Types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_management.BookType')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='Books',
        ),
        migrations.RemoveField(
            model_name='books',
            name='Types',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
